const sentences = [
  { kannada: "nimma hesaru yenu?", english: "What is your name?", bengali: "আপনার নাম কী?" },
  { kannada: "nanna hesaru [XYZ].", english: "My name is [XYZ].", bengali: "আমার নাম [XYZ]।" },
  { kannada: "neevu hegiddiri?", english: "How are you?", bengali: "আপনি কেমন আছেন?" },
  { kannada: "nanu chennagiddini.", english: "I am fine.", bengali: "আমি ভাল আছি।" },
  { kannada: "dayavittu", english: "Please", bengali: "দয়া করে" },
  { kannada: "dhanyavaadagalu", english: "Thank you", bengali: "ধন্যবাদ" },
  { kannada: "kshamisi", english: "Sorry / Excuse me", bengali: "মাফ করবেন" },
  { kannada: "nimage gothideya?", english: "Do you know?", bengali: "আপনার জানা আছে?" },
  { kannada: "nanage gothu", english: "I know", bengali: "আমার জানা আছে" },
  { kannada: "nanage gothilla", english: "I don’t know", bengali: "আমার জানা নেই" },
  { kannada: "yelli hoguttideera?", english: "Where are you going?", bengali: "আপনি কোথায় যাচ্ছেন?" },
  { kannada: "nanu manege hoguttiddene.", english: "I am going home.", bengali: "আমি বাড়ি যাচ্ছি।" },
  { kannada: "nimma mane yelli ide?", english: "Where is your house?", bengali: "আপনার বাড়ি কোথায়?" },
  { kannada: "ondu nimisha", english: "One moment", bengali: "এক মুহূর্ত" },
  { kannada: "banni illi", english: "Come here", bengali: "এখানে আসুন" },
  { kannada: "illi kuLithu", english: "Sit here", bengali: "এখানে বসুন" },
  { kannada: "neeru kodi", english: "Give me water", bengali: "আমাকে পানি দিন" },
  { kannada: "tindi aayita?", english: "Did you eat?", bengali: "আপনি খেয়েছেন?" },
  { kannada: "nanu tindi maadidde", english: "I had food", bengali: "আমি খেয়েছি" },
  { kannada: "hegide?", english: "How is it?", bengali: "কেমন?" },
  { kannada: "chennagide", english: "It is good", bengali: "ভালো" },
  { kannada: "swalpa help kodi", english: "Please help a little", bengali: "একটু সাহায্য করুন" },
  { kannada: "dayavittu swalpa adjust maadi", english: "Please adjust a little", bengali: "একটু মানিয়ে নিন" },
  { kannada: "yestu?", english: "How much?", bengali: "কত?" },
  { kannada: "hinde hogi", english: "Go back", bengali: "পেছনে যান" },
  { kannada: "mundhe banni", english: "Come forward", bengali: "এগিয়ে আসুন" },
  { kannada: "phone kodu", english: "Give the phone", bengali: "ফোনটা দাও" },
  { kannada: "namaskara guru", english: "Hello buddy", bengali: "নমস্কার বন্ধু" },
  { kannada: "yaake late?", english: "Why are you late?", bengali: "আপনি দেরি কেন করলেন?" },
  { kannada: "ond sari", english: "Once / One time", bengali: "একবার" },
  { kannada: "bega banni", english: "Come fast", bengali: "তাড়াতাড়ি আসুন" },
  { kannada: "summane iru", english: "Stay quiet", bengali: "চুপ থাকো" },
  { kannada: "yavaga?", english: "When?", bengali: "কখন?" },
  { kannada: "ivattu busy ide", english: "Today I’m busy", bengali: "আজ আমি ব্যস্ত" },
  { kannada: "naaLe barthini", english: "I’ll come tomorrow", bengali: "আমি আগামীকাল আসব" },
  { kannada: "dayavittu tagolbedi", english: "Please don’t take it", bengali: "দয়া করে এটা নেবেন না" },
  { kannada: "yen maadta iddira?", english: "What are you doing?", bengali: "আপনি কী করছেন?" },
  { kannada: "ond sala nodi", english: "Just take a look", bengali: "একবার দেখুন" },
  { kannada: "nanage ishta", english: "I like it", bengali: "আমার এটা পছন্দ" },
  { kannada: "ninna jothe barthini", english: "I will come with you", bengali: "আমি তোমার সাথে আসব" },
  { kannada: "time aayitu", english: "It’s time", bengali: "সময় হয়ে গেছে" },
  { kannada: "haalayitu", english: "It got spoiled", bengali: "খারাপ হয়ে গেছে" },
  { kannada: "yen problemu?", english: "What’s the problem?", bengali: "সমস্যাটা কী?" },
  { kannada: "yen solution ide?", english: "What’s the solution?", bengali: "সমাধান কী?" },
  { kannada: "next time nodona", english: "We’ll see next time", bengali: "পরের বার দেখা হবে" },
  { kannada: "chennagi maadu", english: "Do it well", bengali: "ভালো করে করো" },
  { kannada: "baagilu muchu", english: "Close the door", bengali: "দরজা বন্ধ করো" },
  { kannada: "baagilu tere", english: "Open the door", bengali: "দরজা খুলে দাও" },
  { kannada: "swalpa thiliyalla", english: "I don’t understand much", bengali: "আমি তেমন বুঝি না" },
  { kannada: "honge illa", english: "Nothing like that", bengali: "তেমন কিছু নয়" },
  { kannada: "yen aadru helu", english: "Say something", bengali: "কিছু বলো" },
  { kannada: "beda", english: "No / Don’t want", bengali: "না / দরকার নেই" },
  { kannada: "beku", english: "Yes / I want", bengali: "হ্যাঁ / চাই" },
  { kannada: "konege nodana", english: "Let’s see at the end", bengali: "শেষে দেখা হবে" },
  { kannada: "munde nodana", english: "Let’s see later", bengali: "পরে দেখা হবে" },
  { kannada: "olage banni", english: "Come inside", bengali: "ভিতরে আসুন" },
  { kannada: "hogbidi", english: "Leave / Go away", bengali: "যান / চলে যান" },
  { kannada: "sari sari", english: "Okay okay", bengali: "ঠিক আছে ঠিক আছে" },
  { kannada: "kastapatbedi", english: "Don’t struggle", bengali: "কষ্ট কোরো না" },
  { kannada: "sulabhvaagide", english: "It’s easy", bengali: "এটা সহজ" },
  { kannada: "kastavide", english: "It’s difficult", bengali: "এটা কঠিন" },
  { kannada: "ennu swalpa samaya kodi", english: "Give me some time", bengali: "আমাকে একটু সময় দিন" },
  { kannada: "phone charge illa", english: "No phone charge", bengali: "ফোনে চার্জ নেই" },
  { kannada: "ninna mele nambike ide", english: "I trust you", bengali: "আমি তোমার উপর বিশ্বাস করি" },
  { kannada: "nanna mele nambike ideya?", english: "Do you trust me?", bengali: "তুমি কি আমার উপর বিশ্বাস করো?" },
  { kannada: "sigona", english: "Let’s meet", bengali: "চল দেখা করি" },
  { kannada: "ond kelsa ide", english: "I have some work", bengali: "একটা কাজ আছে" },
  { kannada: "beda tension", english: "Don’t worry", bengali: "চিন্তা কোরো না" },
  { kannada: "yen kelabeku?", english: "What do you want to ask?", bengali: "তুমি কী জানতে চাও?" },
  { kannada: "yen ishta?", english: "What do you like?", bengali: "তোমার কী পছন্দ?" },
  { kannada: "nanage swalpa time kodi", english: "Give me a little time", bengali: "আমাকে একটু সময় দিন" },
  { kannada: "ready aagidya?", english: "Are you ready?", bengali: "তুমি কি প্রস্তুত?" },
  { kannada: "nodona, sari aagatte", english: "Let’s see, it will be fine", bengali: "দেখা যাক, ঠিক হয়ে যাবে" },
  { kannada: "yestappa!", english: "How much, man!", bengali: "কত রে বাবা!" },
  { kannada: "aamele maadona", english: "Let’s do it later", bengali: "পরে করব" },
  { kannada: "tumba chennagide", english: "Very nice", bengali: "খুব ভালো" },
  { kannada: "thumba olleya", english: "Very good", bengali: "খুব ভালো" },
  { kannada: "bari helbedi", english: "Don’t lie", bengali: "মিথ্যে বোলো না" },
  { kannada: "satyavannu helu", english: "Tell the truth", bengali: "সত্য কথা বলো" },
  { kannada: "yen samachara?", english: "What’s the news?", bengali: "কী খবর?" },
  { kannada: "hogona swalpa walk ge", english: "Let’s go for a walk", bengali: "চল হাঁটতে যাই" },
  { kannada: "photo kalisu", english: "Send the photo", bengali: "ছবিটা পাঠাও" },
  { kannada: "tumba thanks", english: "Thank you very much", bengali: "অনেক ধন্যবাদ" },
  { kannada: "naanu swalpa late aagtene", english: "I’ll be a little late", bengali: "আমি একটু দেরি করব" },
  { kannada: "yenu problem illa", english: "No problem", bengali: "সমস্যা নেই" },
  { kannada: "channagi nidde maadi", english: "Sleep well", bengali: "ভালো করে ঘুমাও" },
  { kannada: "kalita nodona", english: "Let’s meet tomorrow", bengali: "আগামীকাল দেখা হবে" },
  { kannada: "kelsa mugidu", english: "Work is done", bengali: "কাজ শেষ" },
  { kannada: "nanna jothe banni", english: "Come with me", bengali: "আমার সঙ্গে আসুন" },
  { kannada: "hege baribeku?", english: "How to write?", bengali: "কিভাবে লিখতে হয়?" },
  { kannada: "hege uttara kodabeku?", english: "How should I answer?", bengali: "আমি কীভাবে উত্তর দেব?" },
  { kannada: "illi thumba jana iddare", english: "There are many people here", bengali: "এখানে অনেক লোক আছে" },
  { kannada: "nanage swalpa baye aagide", english: "I’m a little scared", bengali: "আমি একটু ভয় পেয়েছি" },
  { kannada: "neenu nanna friend", english: "You are my friend", bengali: "তুমি আমার বন্ধু" },
  { kannada: "yaake heelilla?", english: "Why didn’t you tell?", bengali: "তুমি কেন বলেনি?" },
  { kannada: "naale morning early hogbeku", english: "Tomorrow morning I need to go early", bengali: "আগামীকাল সকালে তাড়াতাড়ি যেতে হবে" },
  { kannada: "idu yenadru nija?", english: "Is this even true?", bengali: "এটা কি সত্যি?" },
  { kannada: "enadru beku andre heelu", english: "If you want something, tell me", bengali: "কিছু লাগলে বলো" },
  { kannada: "ee class mugitu", english: "This class is over", bengali: "এই ক্লাস শেষ" },
  { kannada: "naanu swalpa tired", english: "I am a little tired", bengali: "আমি একটু ক্লান্ত" },
  { kannada: "enadru maadabeku andre heelu", english: "If you need something done, tell me", bengali: "কিছু করতে বলো" },
  { kannada: "yaake ee vishaya matadthaidira?", english: "Why are you talking about this?", bengali: "তুমি কেন এটা নিয়ে বলছো?" },
  { kannada: "phone switch off ide", english: "The phone is switched off", bengali: "ফোন বন্ধ আছে" },
  { kannada: "message maadi", english: "Send a message", bengali: "মেসেজ পাঠাও" },
  { kannada: "ee avakaasha miss madbedi", english: "Don’t miss this opportunity", bengali: "এই সুযোগটা মিস কোরো না" },
  { kannada: "coffee tagona", english: "Let’s have coffee", bengali: "চলো কফি খাই" },
  { kannada: "signal thumba jam ide", english: "The traffic signal is jammed", bengali: "সিগনালে অনেক জ্যাম" },
  { kannada: "whatsapp nalli message kodi", english: "Send a message on WhatsApp", bengali: "হোয়াটসঅ্যাপে মেসেজ পাঠাও" },
  { kannada: "dayavittu avnige heelbedi", english: "Please don’t tell him", bengali: "ওকে বলো না দয়া করে" },
  { kannada: "avaru olleyavaru", english: "He is a good person", bengali: "তিনি একজন ভালো মানুষ" },
  { kannada: "avanu tumba busy", english: "He is very busy", bengali: "সে খুব ব্যস্ত" },
  { kannada: "naanu late agtini", english: "I’ll be late", bengali: "আমি দেরি করব" },
  { kannada: "book kalisi", english: "Send the book", bengali: "বইটা পাঠাও" },
  { kannada: "aa hotel nalli hogona", english: "Let’s go to that hotel", bengali: "চলো ওই হোটেলে যাই" },
  { kannada: "yaake yellaru nodta iddare?", english: "Why is everyone staring?", bengali: "সবাই কেন তাকিয়ে আছে?" },
  { kannada: "manege hoga beku", english: "Need to go home", bengali: "বাড়ি যেতে হবে" },
  { kannada: "last week nodide", english: "I saw it last week", bengali: "গত সপ্তাহে দেখেছি" },
  { kannada: "yestu dina aagide?", english: "How many days has it been?", bengali: "কত দিন হয়ে গেছে?" },
  { kannada: "password marathide", english: "I forgot the password", bengali: "পাসওয়ার্ড ভুলে গেছি" },
  { kannada: "tumba bisi ide", english: "It’s too hot", bengali: "খুব গরম" },
  { kannada: "tumba cold ide", english: "It’s very cold", bengali: "খুব ঠান্ডা" },
  { kannada: "hariyo banni", english: "Move aside", bengali: "একটু সরে দাঁড়ান" },
  { kannada: "light haakbeku", english: "Need to turn on the light", bengali: "লাইট জ্বালাতে হবে" },
  { kannada: "yaake banni?", english: "Why did you come?", bengali: "তুমি কেন এসেছো?" },
  { kannada: "prashne kelbedi", english: "Don’t ask questions", bengali: "প্রশ্ন কোরো না" },
  { kannada: "tumba olleyadu", english: "Very nice", bengali: "খুব ভালো" },
  { kannada: "bekadre heli", english: "Tell me if you need", bengali: "প্রয়োজন হলে বলো" },
  { kannada: "music jasti ide", english: "Music is too loud", bengali: "সঙ্গীতটা খুব জোরে বাজছে" },
  { kannada: "yelli idiya?", english: "Where are you?", bengali: "তুমি কোথায়?" },
  { kannada: "neenu swalpa control maadu", english: "You control a bit", bengali: "তুমি একটু নিয়ন্ত্রণ করো" },
  { kannada: "yen keltiya?", english: "What are you asking?", bengali: "তুমি কী জানতে চাইছো?" },
  { kannada: "yen cinema nodidya?", english: "Did you watch any movie?", bengali: "কোনো সিনেমা দেখেছো?" },
  { kannada: "ee meeting mugisona", english: "Let’s end this meeting", bengali: "এই মিটিংটা শেষ করি" },
  { kannada: "task complete madbeku", english: "Need to complete the task", bengali: "টাস্কটা শেষ করতে হবে" },
  { kannada: "aidu nimisha kodi", english: "Give me 5 minutes", bengali: "আমাকে ৫ মিনিট দিন" },
  { kannada: "swalpa easy agi heelu", english: "Say it a bit simply", bengali: "একটু সহজ করে বলো" },
  { kannada: "naan heli andre nodu", english: "Watch if I say", bengali: "আমি বললে দেখো" },
  { kannada: "light off maadu", english: "Turn off the light", bengali: "লাইট নিভাও" },
  { kannada: "ninna nodi santosha aaytu", english: "I’m happy to see you", bengali: "তোমায় দেখে ভালো লাগল" },
  { kannada: "yestu dina henge?", english: "How long like this?", bengali: "আর কতদিন এভাবে?" },
  { kannada: "idakke solution ideya?", english: "Is there a solution to this?", bengali: "এর কোনো সমাধান আছে?" },
  { kannada: "avanige call maadi", english: "Call him", bengali: "তাকে ফোন করো" },
  { kannada: "yenu prayojana illa", english: "There’s no use", bengali: "কোনো কাজ নেই" },
  { kannada: "parking illade ide", english: "There’s no parking", bengali: "পার্কিং নেই" },
  { kannada: "ticket book maadbeku", english: "Need to book the ticket", bengali: "টিকিট বুক করতে হবে" },
  { kannada: "sumne iru", english: "Just stay quiet", bengali: "চুপচাপ থাকো" },
  { kannada: "clean maadu", english: "Clean it", bengali: "পরিষ্কার করো" },
  { kannada: "enadru kudiyoke ideya?", english: "Is there anything to drink?", bengali: "পান করার মতো কিছু আছে?" },
  { kannada: "text maadi", english: "Text me", bengali: "টেক্সট করো" },
  { kannada: "office late aagutte", english: "Office will be late", bengali: "অফিসে দেরি হবে" },
  { kannada: "hege gotthu?", english: "How do you know?", bengali: "তুমি কীভাবে জানো?" },
  { kannada: "helakke swalpa kastavu", english: "It’s a little hard to explain", bengali: "বলা একটু কঠিন" },
  { kannada: "yen helbeku gottila", english: "I don’t know what to say", bengali: "আমি জানি না কী বলব" },
  { kannada: "time irlilla", english: "There was no time", bengali: "সময় ছিল না" },
  { kannada: "naanu busy idde", english: "I was busy", bengali: "আমি ব্যস্ত ছিলাম" },
  { kannada: "help madtiya?", english: "Will you help?", bengali: "তুমি সাহায্য করবে?" },
  { kannada: "ivaga swalpa headache ide", english: "I have a slight headache now", bengali: "এখন একটু মাথা ধরেছে" },
  { kannada: "door open maadi", english: "Open the door", bengali: "দরজা খোলো" },
  { kannada: "fridge nalli yenu ide?", english: "What’s in the fridge?", bengali: "ফ্রিজে কী আছে?" },
  { kannada: "avanu barlilla", english: "He didn’t come", bengali: "সে আসেনি" },
  { kannada: "avaru nanna boss", english: "He is my boss", bengali: "তিনি আমার বস" },
  { kannada: "delivery yavaaga?", english: "When is the delivery?", bengali: "ডেলিভারি কখন?" },
  { kannada: "toothbrush elli ide?", english: "Where is the toothbrush?", bengali: "টুথব্রাশ কোথায়?" },
  { kannada: "coffee ready ideya?", english: "Is coffee ready?", bengali: "কফি কি তৈরি?" },
  { kannada: "chat madona swalpa", english: "Let’s chat a bit", bengali: "আলাপ করি একটু" },
  { kannada: "paper nalli nodu", english: "Check in the paper", bengali: "কাগজে দেখো" },
  { kannada: "recharge maadbeku", english: "Need to recharge", bengali: "রিচার্জ করতে হবে" },
  { kannada: "nanna seat alli kothko", english: "Sit in my seat", bengali: "আমার সিটে বসো" },
  { kannada: "test result bandide", english: "Test result has come", bengali: "পরীক্ষার ফলাফল এসেছে" },
  { kannada: "nanu yen maadbeku?", english: "What should I do?", bengali: "আমার কী করা উচিত?" },
  { kannada: "inniyendu swalpa wait maadi", english: "Wait for a few more minutes", bengali: "আর একটু অপেক্ষা করো" },
  { kannada: "computer on maadi", english: "Turn on the computer", bengali: "কম্পিউটার চালু করো" },
  { kannada: "yen reaction bekilla", english: "No reaction needed", bengali: "কোনো প্রতিক্রিয়া দরকার নেই" },
  { kannada: "idu nanna opinion", english: "This is my opinion", bengali: "এটা আমার মত" },
  { kannada: "avnu swalpa confuse aagbitru", english: "He got a bit confused", bengali: "সে একটু বিভ্রান্ত হয়ে গেছিল" },
  { kannada: "munde heelona", english: "We’ll talk later", bengali: "পরে কথা বলব" },
  { kannada: "app download maadi", english: "Download the app", bengali: "অ্যাপ ডাউনলোড করো" },
  { kannada: "share maadi", english: "Share it", bengali: "শেয়ার করো" },
  { kannada: "reply kodi", english: "Please reply", bengali: "জবাব দিন" },
  { kannada: "yen change illa", english: "No change", bengali: "কোনো পরিবর্তন নেই" },
  { kannada: "ondhu nimisha nillu", english: "Wait a minute", bengali: "এক মিনিট দাঁড়াও" },
  { kannada: "camera switch on maadu", english: "Turn on the camera", bengali: "ক্যামেরা চালু করো" },
  { kannada: "naale barthini", english: "I’ll come tomorrow", bengali: "আমি আগামীকাল আসব" },
  { kannada: "yenadru kelbeku ideya?", english: "Do you have anything to ask?", bengali: "তোমার কিছু জিজ্ঞেস করার আছে?" },
  { kannada: "ninna hesaru yenu?", english: "What is your name?", bengali: "তোমার নাম কী?" },
  { kannada: "naanu bengaluralli iddini", english: "I live in Bangalore", bengali: "আমি বেঙ্গালুরুতে থাকি" },
  { kannada: "nange swalpa help beku", english: "I need a little help", bengali: "আমার একটু সাহায্য দরকার" },
  { kannada: "yaake late aaytu?", english: "Why are you late?", bengali: "তুমি দেরি করলে কেন?" },
  { kannada: "yen kelbeku?", english: "What do you want to ask?", bengali: "তুমি কী জানতে চাও?" },
  { kannada: "tumba busy idde naale heelthini", english: "I was very busy, I’ll tell you tomorrow", bengali: "খুব ব্যস্ত ছিলাম, আগামীকাল বলব" },
  { kannada: "neevu yelli iddiri?", english: "Where are you?", bengali: "আপনি কোথায়?" },
  { kannada: "please swalpa adjust maadi", english: "Please adjust a little", bengali: "অনুগ্রহ করে একটু মানিয়ে নিন" },
  { kannada: "nanu ivaga ready aagta iddini", english: "I’m getting ready now", bengali: "আমি এখন রেডি হচ্ছি" },
  { kannada: "yestu time aaytu?", english: "What’s the time?", bengali: "কত বাজে?" },
  { kannada: "illa swalpa late aagutte", english: "No, I’ll be a little late", bengali: "না, একটু দেরি হবে" },
  { kannada: "online class ide", english: "There’s an online class", bengali: "অনলাইন ক্লাস আছে" },
  { kannada: "nanna bag kottilla", english: "I didn’t get my bag", bengali: "আমার ব্যাগ পাইনি" },
  { kannada: "meeting start aagide", english: "The meeting has started", bengali: "মিটিং শুরু হয়ে গেছে" },
  { kannada: "close the window", english: "Close the window", bengali: "জানালাটা বন্ধ করো" },
  { kannada: "nimage gotthu alva?", english: "You already know, right?", bengali: "আপনার তো জানা আছেই, তাই না?" },
  { kannada: "avanu nanna classmate", english: "He is my classmate", bengali: "সে আমার সহপাঠী" },
  { kannada: "ninna mane yelli?", english: "Where is your house?", bengali: "তোমার বাড়ি কোথায়?" },
  { kannada: "idanna open maadu", english: "Open this", bengali: "এটা খোলো" },
  { kannada: "naale exam ide", english: "Tomorrow is the exam", bengali: "আগামীকাল পরীক্ষা আছে" },
  { kannada: "message node illa", english: "Didn’t check the message", bengali: "মেসেজ দেখিনি" },
  { kannada: "chat madona swalpa", english: "Let’s chat a bit", bengali: "একটু আড্ডা দিই" },
  { kannada: "morning jogge hogona", english: "Let’s go for a morning jog", bengali: "সকালে জগিং করতে যাই" },
  { kannada: "phone charge agilla", english: "Phone didn’t charge", bengali: "ফোন চার্জ হয়নি" },
  { kannada: "idu swalpa difficult", english: "This is a little difficult", bengali: "এটা একটু কঠিন" },
  { kannada: "window open maadi", english: "Open the window", bengali: "জানালা খোলো" },
  { kannada: "avnu manege hoga bittidane", english: "He already went home", bengali: "সে বাড়ি চলে গেছে" },
  { kannada: "yen thoughts idive?", english: "What thoughts do you have?", bengali: "তোমার কী ভাবনা আছে?" },
  { kannada: "change madbeku", english: "We need a change", bengali: "আমাদের একটা পরিবর্তন দরকার" },
  { kannada: "idu swalpa jasti aagide", english: "This is a bit too much", bengali: "এটা একটু বেশিই হয়ে গেছে" },
  { kannada: "video send maadi", english: "Send the video", bengali: "ভিডিও পাঠাও" },
  { kannada: "nanu swalpa late aagthini", english: "I’ll be a little late", bengali: "আমি একটু দেরি করব" },
  { kannada: "daily practice maadi", english: "Practice daily", bengali: "প্রতিদিন অনুশীলন করো" },
  { kannada: "idu simple agide", english: "This is simple", bengali: "এটা সহজ" },
  { kannada: "please seat kothko", english: "Please take a seat", bengali: "অনুগ্রহ করে বসুন" },
  { kannada: "door close maadi", english: "Close the door", bengali: "দরজা বন্ধ করো" },
  { kannada: "answer correct ide", english: "The answer is correct", bengali: "উত্তরটা সঠিক" },
  { kannada: "idu full mistake", english: "This is totally wrong", bengali: "এটা পুরো ভুল" },
  { kannada: "power off aagide", english: "Power is off", bengali: "বিদ্যুৎ নেই" },
  { kannada: "naale baralla", english: "I won’t come tomorrow", bengali: "আমি আগামীকাল আসব না" },
  { kannada: "ninna opinion yenu?", english: "What’s your opinion?", bengali: "তোমার মতামত কী?" },
  { kannada: "topic na change maadi", english: "Change the topic", bengali: "বিষয়টা বদলাও" },
  { kannada: "last time yenu aaytu?", english: "What happened last time?", bengali: "গতবার কী হয়েছিল?" },
  { kannada: "bega maadu", english: "Do it quickly", bengali: "তাড়াতাড়ি করো" },
  { kannada: "nange signal illa", english: "I don’t have signal", bengali: "আমার নেটওয়ার্ক নেই" },
  { kannada: "document ready maadu", english: "Get the document ready", bengali: "ডকুমেন্ট প্রস্তুত করো" },
  { kannada: "evathu bega nidde hogona", english: "Let’s sleep early today", bengali: "আজ একটু তাড়াতাড়ি ঘুমাই" }
];


