const words = [
  { kannada: "bega", english: "Quickly / Soon", bengali: "তাড়াতাড়ি" },
  { kannada: "heLu", english: "Say / Tell", bengali: "বলো" },
  { kannada: "nimage", english: "To you", bengali: "তোমার জন্য" },
  { kannada: "nanna", english: "My", bengali: "আমার" },
  { kannada: "ninna", english: "Your", bengali: "তোমার" },
  { kannada: "avanu", english: "He", bengali: "সে (ছেলে)" },
  { kannada: "avalu", english: "She", bengali: "সে (মেয়ে)" },
  { kannada: "ivanu", english: "This boy", bengali: "এই ছেলে" },
  { kannada: "ivalu", english: "This girl", bengali: "এই মেয়ে" },
  { kannada: "naanu", english: "I", bengali: "আমি" },
  { kannada: "neevu", english: "You (formal)", bengali: "আপনি" },
  { kannada: "namma", english: "Our", bengali: "আমাদের" },
  { kannada: "nimma", english: "Your (formal)", bengali: "আপনার" },
  { kannada: "yenu", english: "What", bengali: "কি" },
  { kannada: "yelli", english: "Where", bengali: "কোথায়" },
  { kannada: "yaake", english: "Why", bengali: "কেন" },
  { kannada: "yaaru", english: "Who", bengali: "কে" },
  { kannada: "hegide", english: "How is", bengali: "কেমন আছো" },
  { kannada: "uttara", english: "Answer", bengali: "উত্তর" },
  { kannada: "praśne", english: "Question", bengali: "প্রশ্ন" },
  { kannada: "bari", english: "Only", bengali: "শুধু" },
  { kannada: "sari", english: "Correct", bengali: "ঠিক" },
  { kannada: "tappu", english: "Wrong / Mistake", bengali: "ভুল" },
  { kannada: "beku", english: "Need / Want", bengali: "চাই" },
  { kannada: "illa", english: "No / Not there", bengali: "না / নেই" },
  { kannada: "ide", english: "There is", bengali: "আছে" },
  { kannada: "hodu", english: "Okay / Fine", bengali: "ঠিক আছে" },
  { kannada: "saaku", english: "Enough", bengali: "পর্যাপ্ত" },
  { kannada: "shubha", english: "Good / Auspicious", bengali: "শুভ" },
  { kannada: "kelasa", english: "Work", bengali: "কাজ" },
  { kannada: "kalike", english: "Learning", bengali: "শেখা" },
  { kannada: "snehita", english: "Friend", bengali: "বন্ধু" },
  { kannada: "sante", english: "Market / Fair", bengali: "বাজার / মেলা" },
  { kannada: "duDDu", english: "Money", bengali: "টাকা" },
  { kannada: "suttu", english: "Around", bengali: "চারপাশে" },
  { kannada: "jothege", english: "With", bengali: "সাথে" },
  { kannada: "mele", english: "Up / On top", bengali: "উপরে" },
  { kannada: "keLage", english: "Down / Below", bengali: "নিচে" },
  { kannada: "baLika", english: "Girl", bengali: "মেয়ে" },
  { kannada: "huduga", english: "Boy", bengali: "ছেলে" },
  { kannada: "shuru", english: "Start / Beginning", bengali: "শুরু" },
  { kannada: "mugiyu", english: "End / Finish", bengali: "শেষ" },
  { kannada: "modalu", english: "Before / First", bengali: "আগে" },
  { kannada: "nantara", english: "After / Then", bengali: "পরে" },
  { kannada: "avashyaka", english: "Necessary", bengali: "প্রয়োজনীয়" },
  { kannada: "sukha", english: "Comfort / Happiness", bengali: "সুখ" },
  { kannada: "dukkha", english: "Sadness", bengali: "দুঃখ" },
  { kannada: "namage", english: "To us", bengali: "আমাদের জন্য" },
  { kannada: "adikke", english: "To that", bengali: "তার জন্য" },
  { kannada: "illi", english: "Here", bengali: "এখানে" },
  { kannada: "olage", english: "Inside", bengali: "ভিতরে" },
  { kannada: "horaTa", english: "Went", bengali: "গেল" },
  { kannada: "bandu", english: "Came", bengali: "এসেছিল" },
  { kannada: "odhu", english: "Read", bengali: "পড়ো" },
  { kannada: "bare", english: "Write", bengali: "লিখো" },
  { kannada: "maatanaadu", english: "Talk / Speak", bengali: "বল" },
  { kannada: "kelu", english: "Listen", bengali: "শোনো" },
  { kannada: "tili", english: "Know / Understand", bengali: "জানো / বোঝো" },
  { kannada: "sariyagi", english: "Properly", bengali: "ভালভাবে" },
  { kannada: "hede", english: "Laugh", bengali: "হাসো" },
  { kannada: "aalisi", english: "Think", bengali: "ভাবো" },
  { kannada: "neene", english: "You yourself", bengali: "তুমি নিজেই" },
  { kannada: "bere", english: "Different / Other", bengali: "ভিন্ন / অন্য" },
  { kannada: "sadhya", english: "Possible", bengali: "সম্ভব" },
  { kannada: "avakaasha", english: "Chance / Opportunity", bengali: "সুযোগ" },
  { kannada: "hosaddu", english: "New", bengali: "নতুন" },
  { kannada: "hale", english: "Old", bengali: "পুরোনো" },
  { kannada: "doorada", english: "Far", bengali: "দূর" },
  { kannada: "hatthira", english: "Near", bengali: "কাছাকাছি" },
  { kannada: "dodda", english: "Big", bengali: "বড়" },
  { kannada: "sanna", english: "Small", bengali: "ছোট" },
  { kannada: "nija", english: "True", bengali: "সত্য" },
  { kannada: "sullu", english: "Lie", bengali: "মিথ্যা" },
  { kannada: "banni", english: "Come (respectfully)", bengali: "আসুন" },
  { kannada: "hoogi", english: "Go (respectfully)", bengali: "যান" },
  { kannada: "kelasa maaDu", english: "Do work", bengali: "কাজ করো" },
  { kannada: "hodi", english: "Hit / Knock", bengali: "আঘাত করো" },
  { kannada: "madi", english: "Wash / Clean", bengali: "পরিষ্কার করো" },
  { kannada: "toLe", english: "Wipe", bengali: "মুছো" },
  { kannada: "beDa", english: "Don't want / No", bengali: "চাই না" },
  { kannada: "ishta", english: "Like / Love", bengali: "পছন্দ" },
  { kannada: "alpa", english: "Little", bengali: "কম" },
  { kannada: "hechchu", english: "More", bengali: "বেশি" },
  { kannada: "oLLe", english: "Good", bengali: "ভালো" },
  { kannada: "keTTaddu", english: "Bad", bengali: "খারাপ" },
  { kannada: "mosaru", english: "Curd", bengali: "দই" },
  { kannada: "anna", english: "Rice / Meal", bengali: "ভাত / খাবার" },
  { kannada: "oota", english: "Meal / Food", bengali: "খাবার" },
  { kannada: "neeru", english: "Water", bengali: "জল" },
  { kannada: "haalu", english: "Milk", bengali: "দুধ" },
  { kannada: "sakkare", english: "Sugar", bengali: "চিনি" },
  { kannada: "uppu", english: "Salt", bengali: "লবণ" },
  { kannada: "huli", english: "Sour / Tamarind dish", bengali: "টক / টক ডাল" },
  { kannada: "kharabeku", english: "Should be spicy", bengali: "ঝাল হওয়া উচিত" },
  { kannada: "thindi", english: "Snack / Tiffin", bengali: "হালকা খাবার" },
  { kannada: "haLi", english: "Pour", bengali: "ঢালো" },
  { kannada: "koDu", english: "Give", bengali: "দাও" },
  { kannada: "taagu", english: "Drink", bengali: "খাও (পান করো)" },
  { kannada: "tinnu", english: "Eat", bengali: "খাও" },
  { kannada: "gadiyaara", english: "Clock / Watch", bengali: "ঘড়ি" },
  { kannada: "maneyalli", english: "At home", bengali: "বাড়িতে" },
  { kannada: "mane", english: "House", bengali: "বাড়ি" },
  { kannada: "tarabe", english: "Bring", bengali: "আনো" },
  { kannada: "sari madisu", english: "Correct it", bengali: "ঠিক করো" },
  { kannada: "kelasa mugisu", english: "Finish work", bengali: "কাজ শেষ করো" },
  { kannada: "haggu", english: "Sit", bengali: "বসো" },
  { kannada: "nillu", english: "Stop", bengali: "থামো" },
  { kannada: "nilluva sthaana", english: "Stop (location)", bengali: "স্টপেজ" },
  { kannada: "baayi", english: "Mouth", bengali: "মুখ" },
  { kannada: "kaalu", english: "Leg / Foot", bengali: "পা" },
  { kannada: "kai", english: "Hand", bengali: "হাত" },
  { kannada: "mooru", english: "Knee", bengali: "হাঁটু" },
  { kannada: "hannu", english: "Fruit", bengali: "ফল" },
  { kannada: "saaguva", english: "Growing / Cultivating", bengali: "চাষ করা" },
  { kannada: "bele", english: "Price / Crop", bengali: "মূল্য / ফসল" },
  { kannada: "maragaLu", english: "Trees", bengali: "গাছগুলো" },
  { kannada: "hoovu", english: "Flower", bengali: "ফুল" },
  { kannada: "moggina", english: "Bud", bengali: "কুঁড়ি" },
  { kannada: "toogisu", english: "Lift / Carry", bengali: "ওঠাও / ধরো" },
  { kannada: "balli", english: "Lizard", bengali: "টিকটিকি" },
  { kannada: "mukke", english: "Piece", bengali: "টুকরো" },
  { kannada: "hatthira banni", english: "Come closer", bengali: "কাছে এসো" },
  { kannada: "dooravagi iru", english: "Stay away", bengali: "দূরে থাকো" },
  { kannada: "thale", english: "Head", bengali: "মাথা" },
  { kannada: "kaN", english: "Eye", bengali: "চোখ" },
  { kannada: "mugilu", english: "Sky", bengali: "আকাশ" },
  { kannada: "bhumi", english: "Earth / Land", bengali: "পৃথিবী / জমি" },
  { kannada: "snehavagi", english: "Lovingly", bengali: "ভালবাসার সাথে" },
  { kannada: "dheera", english: "Brave", bengali: "সাহসী" },
  { kannada: "bhaya", english: "Fear", bengali: "ভয়" },
  { kannada: "nimage gottilva?", english: "Don’t you know?", bengali: "তোমার জানা নেই?" },
  { kannada: "arivu", english: "Knowledge", bengali: "জ্ঞান" },
  { kannada: "vidya", english: "Education", bengali: "শিক্ষা" },
  { kannada: "aase", english: "Desire / Wish", bengali: "ইচ্ছা" },
  { kannada: "parikshe", english: "Exam", bengali: "পরীক্ষা" },
  { kannada: "uttama", english: "Excellent", bengali: "অসাধারণ" },
  { kannada: "sadaa", english: "Always", bengali: "সর্বদা" },
  { kannada: "yavaga", english: "When", bengali: "কখন" },
  { kannada: "ellaru", english: "Everyone", bengali: "সবাই" },
  { kannada: "kelavaru", english: "Some people", bengali: "কিছু মানুষ" },
  { kannada: "hege", english: "How", bengali: "কিভাবে" },
  { kannada: "huttida dina", english: "Birthday", bengali: "জন্মদিন" },
  { kannada: "huttu", english: "Birth", bengali: "জন্ম" },
  { kannada: "snehabhava", english: "Affection", bengali: "স্নেহ" },
  { kannada: "abhivandane", english: "Salutation / Greeting", bengali: "অভিনন্দন / শুভেচ্ছা" },
  { kannada: "shaale", english: "School", bengali: "স্কুল" },
  { kannada: "kaaryakrama", english: "Program / Event", bengali: "অনুষ্ঠান" },
  { kannada: "aata", english: "Game / Play", bengali: "খেলা" },
  { kannada: "vishaya", english: "Topic / Subject", bengali: "বিষয়" },
  { kannada: "modala", english: "First", bengali: "প্রথম" },
  { kannada: "kanasu", english: "Dream", bengali: "স্বপ্ন" },
  { kannada: "kalpane", english: "Idea / Thought", bengali: "ধারণা / চিন্তা" },
  { kannada: "yatre", english: "Journey / Travel", bengali: "ভ্রমণ" },
  { kannada: "nodi", english: "Look / See (formal)", bengali: "দেখুন" },
  { kannada: "hoogu", english: "Send / Let go", bengali: "পাঠাও / ছেড়ে দাও" },
  { kannada: "mathu", english: "Word / Speech", bengali: "কথা" },
  { kannada: "baduku", english: "Life", bengali: "জীবন" },
  { kannada: "preeti", english: "Love / Affection", bengali: "ভালবাসা" },
  { kannada: "bhava", english: "Emotion / Feeling", bengali: "অনুভব / ভাব" },
  { kannada: "namaskaara", english: "Greetings", bengali: "নমস্কার" },
  { kannada: "ondhu", english: "One", bengali: "একটা" },
  { kannada: "hesaru", english: "Name", bengali: "নাম" },
  { kannada: "helu", english: "Tell", bengali: "বলো" },
  { kannada: "banni", english: "Come", bengali: "এসো" },
  { kannada: "hoga", english: "Go", bengali: "যাও" },
  { kannada: "guri", english: "Goal / Aim", bengali: "লক্ষ্য" },
  { kannada: "uttama", english: "Excellent / Best", bengali: "সেরা / উত্তম" },
  { kannada: "sankhya", english: "Number", bengali: "সংখ্যা" },
  { kannada: "sari", english: "Correct / Okay", bengali: "ঠিক / ঠিক আছে" },
  { kannada: "tappu", english: "Wrong / Mistake", bengali: "ভুল" },
  { kannada: "kone", english: "End / Last", bengali: "শেষ" },
  { kannada: "madhuve", english: "Marriage", bengali: "বিয়ে" },
  { kannada: "yuddha", english: "War", bengali: "যুদ্ধ" },
  { kannada: "shanti", english: "Peace", bengali: "শান্তি" },
  { kannada: "samaya", english: "Time", bengali: "সময়" },
  { kannada: "sthala", english: "Place", bengali: "স্থান" },
  { kannada: "kaarya", english: "Work / Task", bengali: "কাজ" },
  { kannada: "bega", english: "Fast / Quickly", bengali: "তাড়াতাড়ি" },
  { kannada: "melu", english: "Better / Above", bengali: "ভাল / উপরে" },
  { kannada: "keelu", english: "Below / Down", bengali: "নিচে" },
  { kannada: "olage", english: "Inside", bengali: "ভিতরে" },
  { kannada: "hora", english: "Outside", bengali: "বাইরে" },
  { kannada: "sariyagi", english: "Properly", bengali: "সঠিকভাবে" },
  { kannada: "kelsa", english: "Job / Work", bengali: "চাকরি / কাজ" },
  { kannada: "padavi", english: "Position / Degree", bengali: "পদ / ডিগ্রি" },
  { kannada: "kelu", english: "Listen", bengali: "শোনো" },
  { kannada: "mathadi", english: "Speak / Talk", bengali: "কথা বলো" },
  { kannada: "sahaya", english: "Help", bengali: "সাহায্য" },
  { kannada: "sangaati", english: "Companion", bengali: "সহচর" },
  { kannada: "vichara", english: "Thought", bengali: "চিন্তা" },
  { kannada: "prashne", english: "Question", bengali: "প্রশ্ন" },
  { kannada: "uttara", english: "Answer", bengali: "উত্তর" },
  { kannada: "shubha", english: "Auspicious / Good", bengali: "শুভ" },
  { kannada: "dore", english: "Get / Receive", bengali: "পাওয়া" },
  { kannada: "siguttade", english: "Will get", bengali: "পাওয়া যাবে" },
  { kannada: "sigalla", english: "Won’t get", bengali: "পাওয়া যাবে না" },
  { kannada: "jaasti", english: "More", bengali: "বেশি" },
  { kannada: "kadime", english: "Less", bengali: "কম" },
  { kannada: "saaku", english: "Enough", bengali: "পর্যাপ্ত / যথেষ্ট" },
  { kannada: "heccu", english: "Much / Many", bengali: "অনেক" },
  { kannada: "eshtu", english: "How much / How many", bengali: "কত" },
  { kannada: "bere", english: "Other / Different", bengali: "ভিন্ন" },
  { kannada: "ondhe", english: "Same / One only", bengali: "একটাই / একই" },
  { kannada: "devara", english: "God’s", bengali: "ভগবানের" },
  { kannada: "pooje", english: "Worship", bengali: "পূজা" },
  { kannada: "dhyana", english: "Meditation", bengali: "ধ্যান" },
  { kannada: "bhaava", english: "Feeling / Mood", bengali: "ভাব / অনুভূতি" },
  { kannada: "kaadhu", english: "Ear", bengali: "কান" },
  { kannada: "naku", english: "Tongue", bengali: "জিহ্বা" },
  { kannada: "hannu naku", english: "Taste the fruit", bengali: "ফল চেখে দেখো" },
  { kannada: "jothege", english: "Together", bengali: "একসাথে" },
  { kannada: "vichitra", english: "Strange", bengali: "অদ্ভুত" },
  { kannada: "madhura", english: "Sweet", bengali: "মিষ্টি" },
  { kannada: "karagu", english: "Bitter", bengali: "তেতো" },
  { kannada: "hasivu", english: "Hunger", bengali: "ক্ষুধা" },
  { kannada: "neeru kudiyiri", english: "Drink water", bengali: "জল খাও" },
  { kannada: "mathe sigona", english: "See you again", bengali: "আবার দেখা হবে" },
  { kannada: "namma", english: "Our", bengali: "আমাদের" },
  { kannada: "nimage", english: "To you", bengali: "তোমার জন্য" },
  { kannada: "enadaru", english: "Anything", bengali: "কিছু" },
  { kannada: "elli", english: "Where", bengali: "কোথায়" },
  { kannada: "avaru", english: "They / That person (respect)", bengali: "তারা / উনি" },
  { kannada: "ivanu", english: "This person (male)", bengali: "এই ছেলে" },
  { kannada: "ivalu", english: "This person (female)", bengali: "এই মেয়ে" },
  { kannada: "nivu", english: "You (plural/respect)", bengali: "আপনি / তোমরা" },
  { kannada: "navu", english: "We", bengali: "আমরা" },
  { kannada: "mathu", english: "And", bengali: "এবং" },
  { kannada: "hatthu", english: "Ten", bengali: "দশ" },
  { kannada: "muru", english: "Three", bengali: "তিন" },
  { kannada: "halavu", english: "Many / Several", bengali: "অনেক" },
  { kannada: "sari illa", english: "Not okay", bengali: "ঠিক না" },
  { kannada: "munde", english: "Front / Ahead", bengali: "সামনে" },
  { kannada: "hindhe", english: "Back / Behind", bengali: "পিছনে" },
  { kannada: "taale", english: "Banana", bengali: "কলা" },
  { kannada: "mavu", english: "Mango", bengali: "আম" },
  { kannada: "sebu", english: "Apple", bengali: "আপেল" },
  { kannada: "drakshi", english: "Grapes", bengali: "আঙুর" },
  { kannada: "nela", english: "Floor / Ground", bengali: "মাটি / জমি" },
  { kannada: "hoda", english: "Lost", bengali: "হারানো" },
  { kannada: "sigide", english: "Found", bengali: "পাওয়া গেছে" },
  { kannada: "meele", english: "On top", bengali: "উপরে" },
  { kannada: "aamele", english: "After that", bengali: "তারপর" },
  { kannada: "modalu", english: "Before", bengali: "আগে" },
  { kannada: "hotte", english: "Stomach", bengali: "পেট" },
  { kannada: "kempu", english: "Red", bengali: "লাল" },
  { kannada: "hasiru", english: "Green", bengali: "সবুজ" },
  { kannada: "bili", english: "White", bengali: "সাদা" },
  { kannada: "kappu", english: "Black", bengali: "কালো" },
  { kannada: "neeli", english: "Blue", bengali: "নীল" },
  { kannada: "haladi", english: "Yellow", bengali: "হলুদ" },
  { kannada: "gulabi", english: "Pink", bengali: "গোলাপি" },
  { kannada: "baagilu", english: "Door", bengali: "দরজা" },
  { kannada: "kitaki", english: "Window", bengali: "জানলা" },
  { kannada: "bati", english: "Light", bengali: "আলো" },
  { kannada: "dampati", english: "Couple (married)", bengali: "দম্পতি" },
  { kannada: "kaige baradu", english: "Don’t touch", bengali: "ছোঁও না" },
  { kannada: "nanna mele banni", english: "Come to me", bengali: "আমার কাছে এসো" },
  { kannada: "bejaar", english: "Upset / Sad", bengali: "খারাপ লাগা / মন খারাপ" },
  { kannada: "chinte beda", english: "Don’t worry", bengali: "চিন্তা করো না" },
  { kannada: "kelasa maadu", english: "Do the work", bengali: "কাজ করো" },
  { kannada: "iruvudu", english: "Exist / Be", bengali: "আছে / থাকা" }
];

